apiVersion: v1
kind: Service
metadata:

  labels:
    run: raydeo-svc
  name: raydeo-svc

spec:
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 31704
  type: NodePort  
  selector:
    app: node-app

